Add support for chatgpt-4o-latest
zurawiki/tiktoken-rs pull request #85
Opened 2024-09-25 13:58 UTC by Congyuwang

2024-10-12 18:19 UTC, zurawiki requested changes
Make sure to add a test here: https://github.com/zurawiki/tiktoken-rs/blob/784f0e53990da982046128d08400f6ba4557fc7f/tiktoken-rs/src/tokenizer.rs#L144

2024-10-12 18:19 UTC, zurawiki commented on tiktoken-rs/src/tokenizer.rs
> +    ("chatgpt-4o-latest", Tokenizer::O200kBase),
Since this is a specific model and not a model prefix. Let's add it to `MODEL_TO_TOKENIZER`.

2024-10-12 18:19 UTC, zurawiki commented
Thanks for the PR. This LGTM after addressing my comments

2024-10-13 07:16 UTC, Congyuwang commented
I've updated the PR and also added a test.

2024-10-14 00:28 UTC, merged